<?php
/**
 * Test class for SteamAPI.
 * Generated by PHPUnit on 2011-08-24 at 08:01:54.
 */
class SteamAPITest extends PHPUnit_Framework_TestCase {
	static function setUpBeforeClass() {
		include '../SteamAPI.class.php';
		include '../SteamAPIDriver.class.php';
	}

	static function tearDownAfterClass() {
	}

	/**
	* Sets up the fixture, for example, opens a network connection.
	* This method is called before a test is executed.
	*/
	protected function setUp() {
	}

	/**
	* Tears down the fixture, for example, closes a network connection.
	* This method is called after a test is executed.
	*/
	protected function tearDown() {
	}

	function test_load_by_username() {
		$driver = new steam\SteamAPIDriver;
		$api = new steam\SteamAPI($driver);
		$api->load('tekmosis');
		$this->assertSame('76561197960550263', $api->information->steamID64);
		return $api;
	}

	function test_load_by_steamid64() {
		$driver = new steam\SteamAPIDriver;
		$api = new steam\SteamAPI($driver);
		$api->load(76561197960550263);
		$this->assertSame('76561197960550263', $api->information->steamID64);
	}

	function test_get_games() {
		$driver = $this->getMock('steam\SteamAPIDriver', array('get_games_xml_url'));
		$driver->expects($this->any())->method('get_games_xml_url')->will($this->returnValue('xml/games.xml'));

		$api = new steam\SteamAPI($driver);
		$api->load('tekmosis');
		$games = $api->get_games();

		$this->assertTrue(is_array($games));
		$this->assertSame(50, count($games));
		$this->assertSame('Dead Rising 2', $games[18]->name);
	}
}
?>