<?php
/**
 * This is a PHPUnit test for the SteamAPI class
 * Generated by PHPUnit on 2011-08-24 at 08:01:54.
 */

include_once 'global_defines.inc.php';
class SteamPrivateAPITest extends PHPUnit_Framework_TestCase {
	static function setUpBeforeClass() {
		include '/projects/php_includes/Neoseeker/SteamAPI/SteamPrivateAPI.php';
	}

	static function tearDownAfterClass() {
	}

	/**
	* Sets up the fixture, for example, opens a network connection.
	* This method is called before a test is executed.
	*/
	protected function setUp() {
	}

	/**
	* Tears down the fixture, for example, closes a network connection.
	* This method is called after a test is executed.
	*/
	protected function tearDown() {
	}

	function test_get_player_summaries() {
		$api = new \Neoseeker\SteamAPI\SteamPrivateAPI;
		$player_info = json_decode($api->get_player_summaries(76561197970553605));
		$this->assertSame('76561197970553605', $player_info->response->players[0]->steamid);
		$this->assertSame('Red', $player_info->response->players[0]->personaname);

		$player_info = $api->get_player_summaries('abc');
		$this->assertSame(null, $player_info);
	}

	function test_get_player_achievements() {
		$api = new \Neoseeker\SteamAPI\SteamPrivateAPI;
		$achievement = json_decode($api->get_player_achievements(22380,76561197970553605));
		$this->assertSame('Fallout: New Vegas', $achievement->playerstats->gameName);
	}
}
?>